Assignment 2

Tasks Is to Create an excel sheet with dummy data
        write. these data into an excel document with 10sheets
        read this excel file with pandas and write the files into 
        10 csv files


Import Numpy to generate a random array that we can use and Pandas libraries to generate a dataframe for creating our excel file with 10sheets


In [108]:


import numpy as np
import pandas as pd

new_multid_arr = np.random.rand(5,5)

print(new_multid_arr)

[[0.52135154 0.46035093 0.98449108 0.50366184 0.28373902]
 [0.75490332 0.54984692 0.29727756 0.25942798 0.67170082]
 [0.87997044 0.52958806 0.92740123 0.0164238  0.276072  ]
 [0.54631981 0.23865998 0.494582   0.79572567 0.80182697]
 [0.37486362 0.04066018 0.313513   0.77206154 0.1853858 ]]


Create the data frame from the random array, and use custome indexes and columns


In [109]:
new_dataframe = pd.DataFrame(data=new_multid_arr, index=['Russia', 'Italy', 'Australia', 'Cuba', 'Botswana'], columns=['Sunny', 'Rainy', 'Autumn', 'Winter', 'Harmattan'])
print(new_dataframe)

              Sunny     Rainy    Autumn    Winter  Harmattan
Russia     0.521352  0.460351  0.984491  0.503662   0.283739
Italy      0.754903  0.549847  0.297278  0.259428   0.671701
Australia  0.879970  0.529588  0.927401  0.016424   0.276072
Cuba       0.546320  0.238660  0.494582  0.795726   0.801827
Botswana   0.374864  0.040660  0.313513  0.772062   0.185386


Write this data frame into 10 excel sheet and create the xlsx file with pandas

In [110]:
df_sht1 = new_dataframe.copy()


with pd.ExcelWriter('ikechukwu_.xlsx') as writer:
    df_sht1.to_excel(writer, sheet_name='Sheet1')
    df_sht1.to_excel(writer, sheet_name='Sheet2')
    df_sht1.to_excel(writer, sheet_name='Sheet3')
    df_sht1.to_excel(writer, sheet_name='Sheet4')
    df_sht1.to_excel(writer, sheet_name='Sheet5')
    df_sht1.to_excel(writer, sheet_name='Sheet6')
    df_sht1.to_excel(writer, sheet_name='Sheet7')
    df_sht1.to_excel(writer, sheet_name='Sheet8')
    df_sht1.to_excel(writer, sheet_name='Sheet9')
    df_sht1.to_excel(writer, sheet_name='Sheet10')


Reading the excel file


In [111]:
excel_dict = pd.read_excel('judy_.xlsx', index_col=0, sheet_name=None)

Create 10 csv's from the ordered dictionary gotten. from. reading the excel document

In [112]:
for data in excel_dict:
    excel_dict[data].to_csv(data+'.csv', index=False )

Finish !!